### ISSUE TITLE
Vuid not found issue

### ISSUE THREAD

**Issue by Dandroid5000** [made-to-engage/ODP.VisitorGroups#11]
I have observered that some customers that are part of a Real Time Segment in ODP are not being matched to a paired CMS visitor group.

I have debugged the issue via the GraphQl explorer and uncovered that when this happens, their vuid does not exist in ODP... and I also note that your library tries to match customers to ODP Real Time Segments (or audiences) by their vuid. 

I'm not quite sure what's going on here. My best guess (and I could well be wrong) is that when ODP stitches customer records across different sessions, devices, browsers etc, it discards all but one of the vuids. If the vuid I have stored in my cookies is not the one kept against my customer record in ODP then I cannot leverage personalization via your package. 

Not sure I'm making sense... so here's an example...

Joe Bloggs visits a website on his phone. This website is using OPD and Optimizely CMS and linked-up using your package. When he visits the site for the first time, this creates a cookie with a 'vuid' in his phone and sends its value to ODP with all subsequent requests. Joe later registers on the site and his email is captured in ODP. At this point, Joe's customer record in ODP contains his email and his 'vuid'. 

Later on, Joe visits the same website on his desktop. This creates a new cookie with a new vuid in his desktop and sends this to ODP with all subsequent requests. Joe then signs-in on the website via his desktop and his email is again captured in ODP. At this point, ODP has two 'vuid' values that can be attributed to Joe Blogs' customer record.

If ODP keeps the value from his phone against his customer record (and discards the other), then when he browses from his desktop, he will never match the odp audience and never get a personalized experience via the cms visitor groups. 

Does this all make sense? Am I missing anything?

This would seem like a big problem with ODP and personalization, i.e. not being able to do personalization across different channels. 

I think for your package to get around it, ODP would need to expose a _list_ of vuids against each customer and allow your package to query that. 

Is there a way around it that you can see?

Thanks in advance

Dan

**Comment by davidknipe** [comment]
Hi Dan

Thanks for raising the issue. I can confirm that vuid's are certainly not discarded when profiles are stitched. See below for an example:

<img width="1001" alt="image" src="https://github.com/unrvld/ODP.VisitorGroups/assets/6765939/7817a0c0-6cc1-4009-8e26-b4787c31454c">

Can you post an example of how the email is captured (i.e the user is identified) in ODP? Is this a manual identify event in ODP or something else? 

The key point for me is "their vuid does not exist in ODP", is this permanent or only under certain circumstances? 

Many thanks

David

**Comment by andrewmarkham** [comment]
Hi @Dandroid5000 

Are you able to find the user within ODP and then check the vuid against the stored identifiers?  I would like to see whether these correlate.

Thanks

Andy

**Comment by Dandroid5000** [comment]
Hi @andrewmarkham  and @davidknipe 
Thanks so much for your quick responses!
I can now see that ODP is indeed keeping a list of vuids and that if you search for any of them via the GraphQL endpoint, it does indeed return the same/correct customer. 
I did not realise that the library and ODP are stripping the '-' from the vuid, so when I searched for the customer using the exact value in the cookie, it was not being returned. 
Thanks for helping me get to the bottom of it. 
You can close this one. 
Cheers
Dan
