### ISSUE TITLE
Some GraphQL queries are inefficient

### ISSUE THREAD

**Issue by stefanolsen** [made-to-engage/ODP.VisitorGroups#12]
A client of mine is looking into using this add-on. During testing, I have found some queries to be slow and wrote some changes.

However, I am missing push access to push a feature branch in order to make a PR.

**Comment by andrewmarkham** [comment]
Hi @stefanolsen 

You should have write access now.

**Comment by stefanolsen** [comment]
Added a PR #13 to remove the audience count queries.

**Comment by andrewmarkham** [comment]
Hi @stefanolsen 

I am going to pass this over to @davidknipe to take a look at.   The approach you have just taken out was put in place to handle some timeout/performance issues when there was a lot of Real Time Segments.  I just want to ensure that we are not reverting back to that behaviour with your PR.

Thanks
