### ISSUE TITLE
Some Online Data Platform Criteria are not working.

### ISSUE THREAD

**Issue by mttwParagon** [made-to-engage/ODP.VisitorGroups#18]
For the example visitor group, Any account with first name ‘Admin’ should be apart if the visitor group. Verifying the information on ODP, the user [admin@chadwellsupply.com](mailto:admin@chadwellsupply.com) should be apart of the group
![6c5bf9de-7214-4ee4-a2e7-de5f2237e59e](https://github.com/unrvld/ODP.VisitorGroups/assets/88038960/b78352b0-1a22-4100-8526-4de51727f04c)
![7da9bb3f-2013-4d70-862a-c80f40319ce9](https://github.com/unrvld/ODP.VisitorGroups/assets/88038960/6a017a89-7047-40d9-8cfc-589ed5b6dbe3)
However this user doesn't trigger the group when used to personalize content or show on our user-debug page where we list out our visitor groups that a user matches.
![519b4610-9fbe-46bf-8ef1-61f2b8437187](https://github.com/unrvld/ODP.VisitorGroups/assets/88038960/72b4a7cb-7989-41e1-a334-74d2e6f316e7)

   Our Configuration:
    "OdpVisitorGroupOptions": {
      "OdpCookieName": "vuid",
      "CacheTimeoutSeconds": 1,
      "OdpEndpoints": [
        {
          "Name": "US", //Unique name for the instance
          "BaseEndPoint": "https://api.zaius.com",
          "PrivateApiKey": "[Key]"
        }
      ]
    },

From startup.cs
    public void ConfigureServices(IServiceCollection services)
    {
        // set the data directory
        AppDomain.CurrentDomain.SetData("DataDirectory", Path.Combine(_webHostingEnvironment.ContentRootPath, "App_Data"));

        // configure application cookie
        services.ConfigureApplicationCookie(options =>
        {
            options.Cookie.SameSite = SameSiteMode.None;
            options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
        });

        services.Configure<CookiePolicyOptions>(options =>
        {
            options.MinimumSameSitePolicy = SameSiteMode.None;
        });

        services.Configure<FormOptions>(options =>
        {
            options.ValueCountLimit = int.MaxValue;
        });

        // custom configuration
        services.ConfigureSerilogLogging(_config);
        services.ConfigureAzureServiceBus(_config);
        services.ConfigureApplicationServices(_config);
        services.ConfigureChadwellIdentity(_config);
        services.ConfigurePunchout();
        services.ConfigureAssociations();
        services.ConfigureGetaNotFoundHandler(_config);
        services.ConfigureUploadOptions(_config);

        services.AddCms()
              .Configure<MvcOptions>(m =>
              {
                  m.ModelMetadataDetailsProviders.Add(new CustomModelMetadataProvider());//custom model attributes for validation in cms admin
              })
            .AddCommerce() // set up commerce admin, wire up commerce routs  for categories and product pages.
            .AddFind()     // add find admin
            .AddFindSearchProvider() // add default find services
            .AddAdminUserRegistration()
            .AddEmbeddedLocalization<Startup>()
            .AddApplicationInsightsTelemetry()
            .AddHttpContextAccessor()
            .AddMemoryCache()
            .AddCmsTagHelpers() //Epi Tag-helpers
            .AddSitemaps(x => //geta sitemaps
            {
                x.EnableLanguageDropDownInAdmin = false;
                x.EnableRealtimeCaching = true;
                x.EnableRealtimeSitemap = false;
            }, p => p.RequireRole(Roles.Administrators)).AddSitemapsCommerce()
            .AddCustomFindServices(_config);//register custom find services, run at the end.

        services.AddControllersWithViews()
              .AddNewtonsoftJson(options =>
              {
                  options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore; //Avoid runtime errors serializing page ViewModels with a page reference.
              })
              .AddMvcOptions(options => options.Filters.Add(
                  new ResponseCacheAttribute
                  {
                      NoStore = true,
                      Location = ResponseCacheLocation.None
                  }));

        **services.AddODPVisitorGroups();**
        services.AddTinyMceConfiguration();
        services.AddSingleton<IActionContextAccessor, ActionContextAccessor>();

        //Run last to override built in Epi Cart Validation as it doesn't function correctly in Commerce 14.  
        services.AddTransient<OrderValidationService, CustomOrderValidationService>();

        services.AddCors(options =>
        {
            options.AddPolicy("AllowAll", builder =>
            {
                builder.AllowAnyOrigin()
                       .AllowAnyMethod()
                       .AllowAnyHeader();
            });
        });
    }

How we check if a user matches a visitor group on our debug page:

private List<string> GetVisitorGroupByCurrentUser()
{
    var filteredVisitorGroup = new List<string>();
    
    var user = HttpContext.User;
    var visitorGroups = _visitorGroupRepository.List();
    foreach (var visitorGroup in visitorGroups)
    {
        if (_visitorGroupRoleRepository.TryGetRole(visitorGroup.Name, out VisitorGroupRole virtualRoleObject))
        {

            if (virtualRoleObject.IsMatch(user, HttpContext))
            {
                filteredVisitorGroup.Add(visitorGroup.Name);
            }
        }
    }

    return filteredVisitorGroup;
}

I have gotten the  'is in segment'  to work, but not the 'Customer property - Text' nor 'Customer property -Number' criteria.  Do you have any idea why these criteria are not working?

**Comment by andrewmarkhamUNRVLD** [comment]
Hi, @mttwParagon 

I am away at the moment, but I will take a look next week.

**Comment by andrewmarkham** [comment]
Hi, @mttwParagon 

I have found an issue with the 'Customer property - Text', and am putting a fix in now.  I cannot find any problem with the criteria 'Customer property - Number', can you test again and let me know if you can recreate the problem.

I will message you again once the bug has been fixed.

Andy

**Comment by andrewmarkham** [comment]
Hi @mttwParagon 
A fix is now available, please download V2.0.2.  This should be available within the next 24hrs on the optimizely feed.
