### ISSUE TITLE
The type "...." could not be loaded

### ISSUE THREAD

**Issue by MrCSharp22** [made-to-engage/ODP.VisitorGroups#25]
Hi, after an update to the package, we noticed the following error in every audience that used the `AudienceCriterion`.

The error is:

`UNRVLD.ODP.VisitorGroups.Criteria.AudienceCriterion, UNRVLD.ODP.VisitorGroups` 

and it appears on the audience UI in the CMS admin:

![image](https://github.com/user-attachments/assets/12cfbd65-2cb7-4531-a59d-189b15ce1f4d)

I have tracked this to a refactor in the class where the namespace has changed. I am not sure exactly when this change happened, but here's how the class looked like last year vs now:

![image](https://github.com/user-attachments/assets/cf5fb98d-3a25-4b8d-a466-6b4b1465a7bd)

and now:
![image](https://github.com/user-attachments/assets/df817f69-b407-4b8b-bc63-f6819aff7746)

I can fix this on production by running this script:

```sql
update dbo.tblSystemBigTable set String03 = 'UNRVLD.ODP.VisitorGroups.Criteria.Criterion.AudienceCriterion, UNRVLD.ODP.VisitorGroups'
where String03 = 'UNRVLD.ODP.VisitorGroups.Criteria.AudienceCriterion, UNRVLD.ODP.VisitorGroups'
```

I did a test with a custom criterion where I use the `TypeGuid` in the `VisitorGroupCriterion` attribute and it still broke after I renamed the class and changed the namespace so I don't think that would help in this case.

It would be good to have such changed called out in the release notes if possible.

**Comment by andrewmarkham** [comment]
Hi @MrCSharp22,

Apologies. I was aware of the breaking change and thought I had mentioned it in the release notes. Obviously, this wasn't the case. I will make an update.

Another approach is to delete the visitor groups and recreate them, that's what I did.

**Comment by MrCSharp22** [comment]
No problem @andrewmarkham. I thought it was best to put this on your radar.

For us it was a bit faster to apply the fix through SQL than re-configure the audiences.

I'll close this issue as I don't see a way to have an issue like this fixed through a library update.

Thanks :)
