### ISSUE TITLE
ODP.VistorGroups doesn't work with RestSharp 1.0.8

### ISSUE THREAD

**Issue by mttwParagon** [made-to-engage/ODP.VisitorGroups#7]
We've recently updated our solution to the latest version (1.0.8) of RestSharp but now can no longer access the VistorGroups tab in the CMS.
 When I remove this package I can access visitor groups as expected.  

The error we receive is:
Could not load file or assembly 'RestSharp, Version=107.3.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. 

![Capture](https://user-images.githubusercontent.com/88038960/189223252-8f208092-8c8d-46f4-91ba-b377a53726b0.PNG)

**Comment by davidknipe** [comment]
You can resolve this issue with an [assembly redirect](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions). 

I have committed an [update to the test site](https://github.com/made-to-engage/ODP.VisitorGroups/commit/73a17cb12dd5656793cc22ca5b5f8d945ba9d2a3) that updated RestSharp, recreated the issue above and resolved with the assembly redirect. Specifically here's the redirect (ensure the version is the same as the version of RestSharp you have installed): https://github.com/made-to-engage/ODP.VisitorGroups/blob/main/src/DemoSite461/Web.config#L285
